name: "AWS ECR Deploy Image"
description: "Build, tag, and push a Docker image to AWS ECR"

inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  repository:
    description: "Name of the ECR repository"
    required: true
  tags:
    description: "Tags to apply (comma-separated)"
    required: true
  dockerfile-path:
    description: "Path to Dockerfile"
    default: "."
  build-args:
    description: "Build arguments (format: arg1=value1,arg2=value2)"
    required: false

runs:
  using: "node20"
  main: "index.js"
