name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install gulp globally
      run: npm install -g gulp-cli
    
    - name: Production Build
      run: gulp prod
      
    - name: Check dist directory exists
      run: |
        if [ ! -d "dist" ]; then
          echo "Dist directory not created!"
          exit 1
        fi
    
    - name: Verify critical files exist
      run: |
        files=(
          "dist/index.html"
          "dist/assets/css/styles.min.css"
        )
        for file in "${files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Missing file: $file"
            exit 1
          fi
        done

    - name: HTML Validation
      run: |
        npx html-validate "dist/**/*.html"
        
    - name: Check file sizes
      run: |
        if [ -f "dist/assets/css/styles.min.css" ]; then
          css_size=$(stat -f%z "dist/assets/css/styles.min.css" 2>/dev/null || stat -c%s "dist/assets/css/styles.min.css")
          echo "CSS size: $css_size bytes"
          if [ "$css_size" -gt 500000 ]; then
            echo "Warning: CSS file is larger than 500KB"
          fi
        fi
        
    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist ${{ matrix.node-version }}
        path: dist/
        retention-days: 7