name: Mossly.io

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # AWS
  AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  # Build settings
  NODE_VERSION: 20.x
  GULP_BUILD_TASK: prod
  GULP_BUILD_PATH: dist
  # FILE PATHS
  INDEX_FILE_PATH: dist/index.html
  CSS_FILE_PATH: dist/assets/css/styles.min.css

jobs:
  build:
    name: Build [ Gulp ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build project
        uses: scottyrichardson/github-actions/.github/actions/gulp-build@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          gulp-build-task: ${{ env.GULP_BUILD_TASK }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GULP_BUILD_PATH }}
          path: ${{ env.GULP_BUILD_PATH }}
          retention-days: 7

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GULP_BUILD_PATH }}
          path: ${{ env.GULP_BUILD_PATH }}

      - name: Validate index file
        uses: scottyrichardson/github-actions/.github/actions/validate-file@v1
        with:
          file-path: ${{ env.INDEX_FILE_PATH }}

      - name: Validate CSS file
        uses: scottyrichardson/github-actions/.github/actions/validate-file@v1
        with:
          file-path: ${{ env.CSS_FILE_PATH }}

      - name: Validate HTML
        uses: scottyrichardson/github-actions/.github/actions/validate-html@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          source-path: ${{ env.GULP_BUILD_PATH }}
